<?php $isEdit = !empty($student['id']); $selectedParents = $student['parent_ids'] ?? []; ?>
<div class="page-heading"><div><p class="eyebrow">Admissions</p><h1><?= $isEdit ? 'Edit Student' : 'Create Student' ?></h1></div><a class="btn btn-outline-secondary" href="<?= e(url('/students')) ?>"><i class="bi bi-arrow-left me-2"></i>Back</a></div>
<section class="panel">
    <form class="row g-3" method="post" action="<?= e($isEdit ? url('/students/update') : url('/students')) ?>">
        <?= csrf_field() ?><?php if ($isEdit): ?><input type="hidden" name="id" value="<?= e($student['id']) ?>"><?php endif; ?>
        <div class="col-md-3"><label class="form-label">Admission No</label><input class="form-control <?= isset($errors['admission_no']) ? 'is-invalid' : '' ?>" name="admission_no" value="<?= e($student['admission_no'] ?? '') ?>"></div>
        <div class="col-md-3"><label class="form-label">Matriculation No</label><input class="form-control <?= isset($errors['matriculation_no']) ? 'is-invalid' : '' ?>" name="matriculation_no" value="<?= e($student['matriculation_no'] ?? '') ?>" placeholder="e.g. CS/ND/26/001"></div>
        <div class="col-md-3"><label class="form-label">First Name</label><input class="form-control <?= isset($errors['first_name']) ? 'is-invalid' : '' ?>" name="first_name" value="<?= e($student['first_name'] ?? '') ?>"></div>
        <div class="col-md-3"><label class="form-label">Last Name</label><input class="form-control <?= isset($errors['last_name']) ? 'is-invalid' : '' ?>" name="last_name" value="<?= e($student['last_name'] ?? '') ?>"></div>
        <div class="col-md-3"><label class="form-label">Gender</label><select class="form-select" name="gender"><?php foreach (['male','female','other'] as $value): ?><option value="<?= e($value) ?>" <?= ($student['gender'] ?? '') === $value ? 'selected' : '' ?>><?= e(ucfirst($value)) ?></option><?php endforeach; ?></select></div>
        <div class="col-md-4"><label class="form-label">Class</label><select class="form-select" name="class_stream_id"><option value="">Unassigned</option><?php foreach ($classes as $class): ?><option value="<?= e($class['id']) ?>" <?= (string)($student['class_stream_id'] ?? '') === (string)$class['id'] ? 'selected' : '' ?>><?= e($class['name'] . ' ' . $class['stream']) ?></option><?php endforeach; ?></select></div>
        <div class="col-md-4"><label class="form-label">Email</label><input class="form-control <?= isset($errors['email']) ? 'is-invalid' : '' ?>" name="email" type="email" value="<?= e($student['email'] ?? '') ?>"></div>
        <div class="col-md-4"><label class="form-label">Phone</label><input class="form-control" name="phone" value="<?= e($student['phone'] ?? '') ?>"></div>
        <div class="col-md-3"><label class="form-label">Date of Birth</label><input class="form-control" type="date" name="date_of_birth" value="<?= e($student['date_of_birth'] ?? '') ?>"></div>
        <div class="col-md-3"><label class="form-label">Nationality</label><input class="form-control" name="nationality" value="<?= e($student['nationality'] ?? '') ?>"></div>
        <div class="col-md-3"><label class="form-label">Religion</label><input class="form-control" name="religion" value="<?= e($student['religion'] ?? '') ?>"></div>
        <div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach (['active','transferred','graduated','suspended','inactive'] as $value): ?><option value="<?= e($value) ?>" <?= ($student['status'] ?? 'active') === $value ? 'selected' : '' ?>><?= e(ucfirst($value)) ?></option><?php endforeach; ?></select></div>
        <div class="col-md-6"><label class="form-label">Parents / Guardians</label><select class="form-select" name="parent_ids[]" multiple size="4"><?php foreach ($parents as $parent): ?><option value="<?= e($parent['id']) ?>" <?= in_array($parent['id'], $selectedParents) ? 'selected' : '' ?>><?= e($parent['name'] . ' · ' . $parent['phone']) ?></option><?php endforeach; ?></select></div>
        <div class="col-md-6"><label class="form-label">Emergency Contact</label><input class="form-control" name="emergency_contact" value="<?= e($student['emergency_contact'] ?? '') ?>"><label class="form-label mt-3">Previous School</label><input class="form-control" name="previous_school" value="<?= e($student['previous_school'] ?? '') ?>"></div>
        <div class="col-12"><label class="form-label">Medical Notes</label><textarea class="form-control" name="medical_notes" rows="3"><?= e($student['medical_notes'] ?? '') ?></textarea></div>
        <div class="col-12 d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="<?= e(url('/students')) ?>">Cancel</a><button class="btn btn-primary">Save Student</button></div>
    </form>
</section>
