<div class="page-heading"><div><p class="eyebrow">Phase 3</p><h1>Fees</h1></div><button class="btn btn-outline-secondary" onclick="window.print()"><i class="bi bi-printer me-2"></i>Print</button></div>
<div class="row g-4">
    <?php if (\App\Core\Auth::can('finance.manage')): ?>
    <div class="col-xl-6"><section class="panel"><h2 class="h5 mb-3">Create Invoice</h2><form class="row g-3" method="post" action="<?= e(url('/fees/invoice')) ?>"><?= csrf_field() ?><div class="col-md-6"><label class="form-label">Student</label><select class="form-select" name="student_id"><?php foreach ($students as $student): ?><option value="<?= e($student['id']) ?>"><?= e($student['admission_no'] . ' · ' . $student['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Academic Session / Semester</label><select class="form-select" name="term_id"><option value="">Select semester</option><?php foreach ($terms as $term): ?><option value="<?= e($term['id']) ?>"><?= e($term['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Invoice No</label><input class="form-control" name="invoice_no" value="<?= e($nextInvoiceNo) ?>"></div><div class="col-md-4"><label class="form-label">Amount</label><input class="form-control" type="number" step="0.01" name="amount"></div><div class="col-md-4"><label class="form-label">Due Date</label><input class="form-control" type="date" name="due_date"></div><div class="col-12"><label class="form-label">Description</label><input class="form-control" name="description" value="Tuition and activities"></div><div class="col-12"><button class="btn btn-primary">Create Invoice</button></div></form></section></div>
    <div class="col-xl-6"><section class="panel"><h2 class="h5 mb-3">Record Payment</h2><form class="row g-3" method="post" action="<?= e(url('/fees/payment')) ?>"><?= csrf_field() ?><div class="col-md-6"><label class="form-label">Invoice</label><select class="form-select" name="invoice_id"><?php foreach ($invoices as $invoice): ?><option value="<?= e($invoice['id']) ?>"><?= e($invoice['invoice_no'] . ' · ' . $invoice['student_name'] . ' · Bal ' . number_format((float)$invoice['balance'])) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Receipt No</label><input class="form-control" name="receipt_no" value="<?= e($nextReceiptNo) ?>"></div><div class="col-md-4"><label class="form-label">Amount</label><input class="form-control" type="number" step="0.01" name="amount_paid"></div><div class="col-md-4"><label class="form-label">Method</label><select class="form-select" name="payment_method"><?php foreach (['cash','bank','card'] as $method): ?><option value="<?= e($method) ?>"><?= e(ucfirst($method)) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Reference</label><input class="form-control" name="payment_reference"></div><div class="col-12"><button class="btn btn-primary">Record Payment</button></div></form></section></div>
    <?php endif; ?>
    <?php if (\App\Core\Auth::can('finance.manage')): ?>
    <div class="col-12"><section class="panel"><h2 class="h5 mb-3">Pending Payment Verification</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Receipt</th><th>Student</th><th>Invoice</th><th>Amount</th><th>Method</th><th>Reference</th><th>Action</th></tr></thead><tbody><?php foreach ($pendingPayments as $payment): ?><tr><td><?= e($payment['receipt_no']) ?></td><td><?= e($payment['student_name']) ?></td><td><?= e($payment['invoice_no']) ?></td><td><?= e(number_format((float)$payment['amount_paid'], 2)) ?></td><td><?= e($payment['payment_method']) ?></td><td><?= e($payment['payment_reference'] ?? '—') ?></td><td><div class="d-flex gap-2"><?php if (\App\Core\Auth::can('finance.manage')): ?><form method="post" action="<?= e(url('/fees/verify')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($payment['id']) ?>"><input type="hidden" name="decision" value="verified"><button class="btn btn-sm btn-success" type="submit">Verify</button></form><form method="post" action="<?= e(url('/fees/verify')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($payment['id']) ?>"><input type="hidden" name="decision" value="rejected"><button class="btn btn-sm btn-outline-danger" type="submit">Reject</button></form><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div></section></div>
    <?php endif; ?>
    <div class="col-12"><section class="panel"><h2 class="h5 mb-3">Invoices</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Invoice</th><th>Student</th><th>Description</th><th>Amount</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php foreach ($invoices as $invoice): ?><tr><td><?= e($invoice['invoice_no']) ?></td><td><?= e($invoice['student_name']) ?></td><td><?= e($invoice['description']) ?></td><td><?= e(number_format((float)$invoice['amount'], 2)) ?></td><td><?= e(number_format((float)$invoice['balance'], 2)) ?></td><td><span class="badge text-bg-secondary"><?= e($invoice['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div></section></div>
    <div class="col-12"><section class="panel"><h2 class="h5 mb-3">Recent Payments</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Receipt</th><th>Invoice</th><th>Student</th><th>Amount</th><th>Method</th><th>Status</th><th>Date</th></tr></thead><tbody><?php foreach ($payments as $payment): ?><tr><td><a href="<?= e(url('/fees/receipt?id=' . $payment['id'])) ?>"><?= e($payment['receipt_no']) ?></a></td><td><?= e($payment['invoice_no']) ?></td><td><?= e($payment['student_name']) ?></td><td><?= e(number_format((float)$payment['amount_paid'], 2)) ?></td><td><?= e($payment['payment_method']) ?></td><td><?= e($payment['payment_status']) ?></td><td><?= e(date('M j, Y H:i', strtotime($payment['paid_at']))) ?></td></tr><?php endforeach; ?></tbody></table></div></section></div>
</div>
